version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: plocek/glpi
    build:
      context: .
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - ./glpi-data/config:/var/www/html/glpi/config
      - ./glpi-data/files:/var/www/html/glpi/files
      - ./glpi-data/marketplace:/var/www/html/glpi/marketplace
      - ./glpi-data/plugins:/var/www/html/glpi/plugins
    environment:
      - TIMEZONE=Europe/Brussels
      - GLPI_REMOVE_INSTALLER=yes
    restart: always
